### ISSUE TITLE
Looking for LaunchBox auto launch game plugin

### ISSUE THREAD

**Issue by AckerApple** [SsjCosty/LaunchboxPlugins#3]
I'm just searching GitHub for anyone doing LaunchBox work. Trying to find a script/plugin that I can have LaunchBox launch a game. Ultimately trying to get LaunchBox where on start up it loads a specific game. 🔎 Internet searching only returns super hacky automated hot key presses with delays between presses, its a mess.

Do you have knowledge or information on how I might do this?

Feel free to close this issue since it is not directly related to your code base.

Thank you kindly. Be well

**Comment by AckerApple** [comment]
I think I found what I was looking for. Closing this issue.

https://github.com/AtomFry/BigBoxAutoPlay

**Comment by CostinTanasoiu** [comment]
I’m glad you found a solution!
